baseurl = "https://patrickphat.com/"
title = "Patrick phat"
theme = "hugo-tania"
paginate: 6
languageCode = "en-us"
params:
  titleEmoji: '😎'
  socialOptions:
    github: 
    twitter: 

menu:
  header:
    - name: Articles
      url: "/articles/"
  footer:
    - name: RSS
      url: "/index.xml"

markup:
  highlight:
    noClasses: false
    lineNos: true
  goldmark:
    renderer:
      unsafe: true
